### ISSUE TITLE
Configurar ambiente de desenvolvimento

### ISSUE THREAD

**Issue by ViniciusPuerto** [Grupo-Olimpo/E-a-Economia#4]
**Descrição**
Configurar o ambiente de desenvolvimento para o backend

**Tasks**

- [x] Levantar dependencias necessárias para inicialização do projeto
- [x] Configurar o banco de dados.
- [x] Configurar estrutura básica de pastas.
- [x] Dockerizar o ambiente

**Comment by ViniciusPuerto** [comment]
https://medium.com/better-programming/dockerizing-react-app-and-express-api-with-mongodb-f3a06bebf570 Um artigo que mostra como podemos fazer a parte do backend
