### ISSUE TITLE
Criar transação

### ISSUE THREAD

**Issue by ViniciusPuerto** [Grupo-Olimpo/E-a-Economia#7]
**Descrição**
Permitir o usuário criar suas transações

**História de usuário**
US05

**Épico**
EP03

**Tasks**

- [x] Fazer CRUD para transações.
- [x] Criar model e suas migrations para transações .
- [ ] Deixar actions permitidas apenas usuários autenticados.

**Comment by giovannabbottino** [comment]
Estou fazendo com base nesse aqui https://bezkoder.com/sequelize-associate-one-to-many/

**Comment by giovannabbottino** [comment]
Cheguei a fazer, mas tive que formatar o pc e perdi tudo
