### ISSUE TITLE
Criar labels

### ISSUE THREAD

**Issue by ViniciusPuerto** [Grupo-Olimpo/E-a-Economia#8]
**Descrição**

**História de Usuário Relacionada**
US03-04

**Requisito Relacionado**
RF02

**Épico Relacionado**
EP02

**Tasks**

- [x] Criar CRUD para Labels.
- [x] Criar model para Label com suas respectivas relações .
- [ ] Permitir acesso apenas para usuários autenticados.
